export default {
  adminDashboard: {
    common: { cancel: "Cancel", ok: "OK", language: "Display language", orders: "orders", revenue: "Revenue", completion: "Completion", metric: "Metric", vendor: "Vendor", unknown: "Unknown", notAvailable: "Not available", normal: "Normal", action: "Action" },
    filters: { allTime: "All time", last7Days: "Last 7 days", lastMonth: "Last Month", last3Months: "Last 3 Months", last6Months: "Last 6 Months", thisYear: "This Year", customDate: "Custom Date", clearFilter: "Clear Filter", filterByDate: "Filter by date", fromTo: "From: {{from}} To: {{to}}", customRange: "Custom Date Range", startDate: "Start Date", endDate: "End Date", back: "Back", apply: "Apply", invalidRange: "End date must be the same as or after the start date." },
    stats: { REVENUE: { title: "Total Revenue" }, ORDERS: { title: "Total Orders" }, ACTIVE_VENDORS: { title: "Active Vendors" }, CUSTOMERS: { title: "Total Customers" }, PENDING_APPROVALS: { title: "Pending Approvals" }, OPEN_SUPPORT: { title: "Open Support" } },
    chart: { title: "Revenue & Order Analytics", last7Description: "Daily platform performance for the last 7 days.", description: "Performance metrics for {{timeframe}}.", revenue: "Revenue", orders: "Orders", ordersValue: "{{formattedCount}} orders", ordersValue_one: "{{formattedCount}} order", ordersValue_other: "{{formattedCount}} orders", loadingTitle: "Loading analytics snapshot", loadingDescription: "Updating revenue and order performance for the selected reporting window.", empty: "No analytics data available for this time range." },
    vendorBreakdown: { title: "Vendor Breakdown", active: "Active Vendors", pending: "Pending Approval", topRated: "Top Rated" },
    topVendors: { title: "Top Performing Vendors", empty: "No vendor performance data available yet." },
    approvals: { title: "Pending Vendor Approvals", description: "Review and manage new vendor applications.", viewVendors: "View Vendors", rowSelection: "Row selection", vendorName: "Vendor Name", type: "Type", location: "Location", submitted: "Submitted", priority: "Priority", status: "Status", actions: "Actions", approveTitle: "Approve Vendor", rejectTitle: "Reject Vendor", setPending: "Set to Pending", setReviewing: "Set to Reviewing", approveVendor: "Approve Vendor", rejectVendor: "Reject Vendor", statuses: { Pending: "Pending", Reviewing: "Reviewing", Approved: "Approved", Rejected: "Rejected" } },
    quickActions: { title: "Quick Actions", vendors: "Approve Vendors", orders: "View Orders", payouts: "Process Payouts", support: "Review Tickets", reports: "View Reports", settings: "Settings" },
    alerts: { sessionExpired: "Your session has expired. Please log in again.", rejectTitle: "Reject vendor application", reasonLabel: "Reason", reasonPlaceholder: "Explain why this vendor is being rejected", rejectConfirm: "Reject", reasonRequired: "A rejection reason is required.", approvalUpdated: "Approval updated", updateFailed: "Update failed", updateFallback: "Unable to update approval status.", loadFallback: "Unable to load dashboard." },
    api: { loadOverviewError: "Unable to load dashboard overview.", updateApprovalError: "Unable to update vendor approval status.", updated: "Approval updated successfully.", unknownVendor: "Unknown vendor" },
  },
};
