export default {
  auth: {
    login: { missingTitle: "Manglende opplysninger", missingText: "Skriv inn e-postadresse og passord.", failedTitle: "Innlogging mislyktes", failedText: "Kontroller administratoropplysningene dine og prøv igjen.", signingIn: "Logger inn …", submit: "Logg inn", forgot: "Glemt passord?", access: "Administratortilgang", email: "E-postadresse", emailPlaceholder: "Skriv inn administratorens e-postadresse", password: "Passord", passwordPlaceholder: "Skriv inn passordet", remember: "Husk meg", subtitle: "Logg inn for å administrere leverandører, bestillinger, utbetalinger og plattformaktivitet.", welcome: "Velkommen tilbake", controlCenter: "Sikker tilgang til kontrollsenteret" },
    forgot: { missingTitle: "Mangler e-postadresse", missingText: "Skriv inn e-postadressen som er knyttet til administratorkontoen.", sentTitle: "Koden er sendt", failedTitle: "Kan ikke sende kode", failedText: "Prøv igjen om et øyeblikk.", sending: "Sender …", submit: "Send kode", back: "Tilbake til innlogging", eyebrow: "Tilbakestilling av passord", email: "E-postadresse", emailPlaceholder: "Skriv inn administratorens e-postadresse", subtitle: "Skriv inn administratorens e-postadresse, så sender vi en bekreftelseskode.", title: "Glemt passordet?" },
  },
  adminDashboard: {
    common: { cancel: "Avbryt", ok: "OK", language: "Visningsspråk", orders: "bestillinger", revenue: "Omsetning", completion: "Fullføring", metric: "Måling", vendor: "Leverandør", unknown: "Ukjent", notAvailable: "Ikke tilgjengelig", normal: "Normal", action: "Handling" },
    filters: { allTime: "Alle tider", last7Days: "Siste 7 dager", lastMonth: "Forrige måned", last3Months: "Siste 3 måneder", last6Months: "Siste 6 måneder", thisYear: "I år", customDate: "Egendefinert dato", clearFilter: "Nullstill filter", filterByDate: "Filtrer etter dato", fromTo: "Fra: {{from}} Til: {{to}}", customRange: "Egendefinert datoperiode", startDate: "Startdato", endDate: "Sluttdato", back: "Tilbake", apply: "Bruk", invalidRange: "Sluttdatoen må være lik eller etter startdatoen.", previousMonth: "Forrige måned", nextMonth: "Neste måned", today: "I dag", clearDate: "Tøm dato", weekdays: { mon: "Man", tue: "Tir", wed: "Ons", thu: "Tor", fri: "Fre", sat: "Lør", sun: "Søn" }, months: { january: "januar", february: "februar", march: "mars", april: "april", may: "mai", june: "juni", july: "juli", august: "august", september: "september", october: "oktober", november: "november", december: "desember" } },
    stats: { REVENUE: { title: "Total omsetning" }, ORDERS: { title: "Totale bestillinger" }, ACTIVE_VENDORS: { title: "Aktive leverandører" }, CUSTOMERS: { title: "Totale kunder" }, PENDING_APPROVALS: { title: "Venter på godkjenning" }, OPEN_SUPPORT: { title: "Åpne supportsaker" } },
    chart: { title: "Omsetnings- og bestillingsanalyse", last7Description: "Daglig plattformytelse for de siste 7 dagene.", description: "Ytelsesmålinger for {{timeframe}}.", revenue: "Omsetning", orders: "Bestillinger", ordersValue: "{{formattedCount}} bestillinger", ordersValue_one: "{{formattedCount}} bestilling", ordersValue_other: "{{formattedCount}} bestillinger", loadingTitle: "Laster analyseoversikt", loadingDescription: "Oppdaterer omsetning og bestillingsytelse for valgt rapportperiode.", empty: "Ingen analysedata er tilgjengelig for denne perioden." },
    vendorBreakdown: { title: "Leverandøroversikt", active: "Aktive leverandører", pending: "Venter på godkjenning", topRated: "Høyest vurdert" },
    topVendors: { title: "Best presterende leverandører", empty: "Ingen leverandørytelse er tilgjengelig ennå." },
    approvals: { title: "Ventende leverandørgodkjenninger", description: "Se gjennom og administrer nye leverandørsøknader.", viewVendors: "Vis leverandører", rowSelection: "Radvalg", vendorName: "Leverandørnavn", type: "Type", location: "Sted", submitted: "Innsendt", priority: "Prioritet", status: "Status", actions: "Handlinger", approveTitle: "Godkjenn leverandør", rejectTitle: "Avslå leverandør", setPending: "Sett til venter", setReviewing: "Sett til vurdering", approveVendor: "Godkjenn leverandør", rejectVendor: "Avslå leverandør", statuses: { Pending: "Venter", Reviewing: "Under vurdering", Approved: "Godkjent", Rejected: "Avslått" } },
    quickActions: { title: "Hurtighandlinger", vendors: "Godkjenn leverandører", orders: "Vis bestillinger", payouts: "Behandle utbetalinger", support: "Se supportsaker", reports: "Vis rapporter", settings: "Innstillinger" },
    alerts: { sessionExpired: "Økten din er utløpt. Logg inn igjen.", rejectTitle: "Avslå leverandørsøknad", reasonLabel: "Årsak", reasonPlaceholder: "Forklar hvorfor denne leverandøren blir avslått", rejectConfirm: "Avslå", reasonRequired: "Årsak til avslag er påkrevd.", approvalUpdated: "Godkjenning oppdatert", updateFailed: "Oppdatering mislyktes", updateFallback: "Kan ikke oppdatere godkjenningsstatus.", loadFallback: "Kan ikke laste dashbordet." },
    api: { loadOverviewError: "Kan ikke laste dashbordoversikten.", updateApprovalError: "Kan ikke oppdatere leverandørens godkjenningsstatus.", updated: "Godkjenningen er oppdatert.", unknownVendor: "Ukjent leverandør" },
  },
};
