export default {
  adminDashboard: {
    common: { cancel: "Avbryt", ok: "OK", language: "Visningsspråk", orders: "bestillinger", revenue: "Omsetning", completion: "Fullføring", metric: "Måling", vendor: "Leverandør", unknown: "Ukjent", notAvailable: "Ikke tilgjengelig", normal: "Normal", action: "Handling" },
    filters: { allTime: "Alle tider", last7Days: "Siste 7 dager", lastMonth: "Forrige måned", last3Months: "Siste 3 måneder", last6Months: "Siste 6 måneder", thisYear: "I år", customDate: "Egendefinert dato", clearFilter: "Nullstill filter", filterByDate: "Filtrer etter dato", fromTo: "Fra: {{from}} Til: {{to}}", customRange: "Egendefinert datoperiode", startDate: "Startdato", endDate: "Sluttdato", back: "Tilbake", apply: "Bruk", invalidRange: "Sluttdatoen må være lik eller etter startdatoen." },
    stats: { REVENUE: { title: "Total omsetning" }, ORDERS: { title: "Totale bestillinger" }, ACTIVE_VENDORS: { title: "Aktive leverandører" }, CUSTOMERS: { title: "Totale kunder" }, PENDING_APPROVALS: { title: "Venter på godkjenning" }, OPEN_SUPPORT: { title: "Åpne supportsaker" } },
    chart: { title: "Omsetnings- og bestillingsanalyse", last7Description: "Daglig plattformytelse for de siste 7 dagene.", description: "Ytelsesmålinger for {{timeframe}}.", revenue: "Omsetning", orders: "Bestillinger", ordersValue: "{{formattedCount}} bestillinger", ordersValue_one: "{{formattedCount}} bestilling", ordersValue_other: "{{formattedCount}} bestillinger", loadingTitle: "Laster analyseoversikt", loadingDescription: "Oppdaterer omsetning og bestillingsytelse for valgt rapportperiode.", empty: "Ingen analysedata er tilgjengelig for denne perioden." },
    vendorBreakdown: { title: "Leverandøroversikt", active: "Aktive leverandører", pending: "Venter på godkjenning", topRated: "Høyest vurdert" },
    topVendors: { title: "Best presterende leverandører", empty: "Ingen leverandørytelse er tilgjengelig ennå." },
    approvals: { title: "Ventende leverandørgodkjenninger", description: "Se gjennom og administrer nye leverandørsøknader.", viewVendors: "Vis leverandører", rowSelection: "Radvalg", vendorName: "Leverandørnavn", type: "Type", location: "Sted", submitted: "Innsendt", priority: "Prioritet", status: "Status", actions: "Handlinger", approveTitle: "Godkjenn leverandør", rejectTitle: "Avslå leverandør", setPending: "Sett til venter", setReviewing: "Sett til vurdering", approveVendor: "Godkjenn leverandør", rejectVendor: "Avslå leverandør", statuses: { Pending: "Venter", Reviewing: "Under vurdering", Approved: "Godkjent", Rejected: "Avslått" } },
    quickActions: { title: "Hurtighandlinger", vendors: "Godkjenn leverandører", orders: "Vis bestillinger", payouts: "Behandle utbetalinger", support: "Se supportsaker", reports: "Vis rapporter", settings: "Innstillinger" },
    alerts: { sessionExpired: "Økten din er utløpt. Logg inn igjen.", rejectTitle: "Avslå leverandørsøknad", reasonLabel: "Årsak", reasonPlaceholder: "Forklar hvorfor denne leverandøren blir avslått", rejectConfirm: "Avslå", reasonRequired: "Årsak til avslag er påkrevd.", approvalUpdated: "Godkjenning oppdatert", updateFailed: "Oppdatering mislyktes", updateFallback: "Kan ikke oppdatere godkjenningsstatus.", loadFallback: "Kan ikke laste dashbordet." },
    api: { loadOverviewError: "Kan ikke laste dashbordoversikten.", updateApprovalError: "Kan ikke oppdatere leverandørens godkjenningsstatus.", updated: "Godkjenningen er oppdatert.", unknownVendor: "Ukjent leverandør" },
  },
};
